
create table
  public.globals (
    gold bigint not null default 0,
    red_ml bigint not null default 0,
    green_ml bigint null default 0,
    blue_ml bigint null default 0,
    dark_ml bigint null default 0,
    potion_inventory bigint null default 0,
    constraint globals_pkey primary key (gold)
  ) tablespace pg_default;

create table
  public.potions (
    potion_id bigint generated by default as identity,
    name text not null,
    potion_type integer[] not null,
    inventory integer not null default 0,
    sku text not null,
    price bigint not null,
    constraint potions_pkey primary key (potion_id)
  ) tablespace pg_default;

insert into
  potions (name, potion_type)
values
  ('red', array[100, 0, 0, 0], 'RED_POTION'),
  ('green', array[0, 100, 0, 0], 'GREEN_POTION'),
  ('blue', array[0, 0, 100, 0], 'BLUE_POTION'),
  ('dark', array[0, 0, 0, 100], 'DARK_POTION'),
  ('purple', array[50, 0, 50, 0], 'PURPLE_POTION'),
  ('yellow', array[50, 50, 0, 0], 'YELLOW_POTION'),
  ('teal', array[0, 50, 50, 0], 'TEAL_POTIONS'),
  ('dark_red', array[50, 0, 0, 50], 'DARK_RED_POTION'),
  ('dark_green', array[0, 50, 0, 50], 'DARK_GREEN_POTION'),
  ('dark_blue', array[0, 0, 50, 50], 'DARK_BLUE_POTION')

create table
  public.carts (
    cart_id bigint generated always as identity,
    name text not null,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    cart_id integer not null,
    potion_id bigint not null,
    quantity integer not null,
    constraint cart_items_pkey primary key (cart_id, potion_id)
  ) tablespace pg_default;